"""Unchanged fictional portfolio catalog, DEMO-001 through DEMO-020."""

DEMO_LISTINGS = [
    {
        "title": "Hearthstone Craftsman",
        "status": "Active",
        "is_public": True,
        "is_featured": True,
        "hide_exact_address": False,
        "price": 289000,
        "property_type": "Single Family",
        "address": "1421 Hearthstone Lane",
        "city": "Story City",
        "state": "IA",
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1680,
        "acreage": 0.22,
        "year_built": 1926,
        "annual_property_taxes": None,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Roland-Story Community School District",
        "amenities": [
            "Original built-ins",
            "Hardwood floors",
            "Enclosed porch",
            "Detached garage",
            "Fenced backyard",
        ],
        "description": "Warm 1920s Craftsman with preserved woodwork, updated kitchen finishes, and a bright enclosed porch. The fenced backyard and detached garage make it a practical in-town home with plenty of character.",
        "mls_number": "DEMO-001",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Prairie Lantern Ranch",
        "status": "Active",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 439000,
        "property_type": "Single Family",
        "address": "908 Prairie Lantern Drive",
        "city": "Story City",
        "state": "IA",
        "bedrooms": 4,
        "bathrooms": 3.0,
        "sqft": 2420,
        "acreage": 0.31,
        "year_built": 2018,
        "annual_property_taxes": None,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Roland-Story Community School District",
        "amenities": [
            "Finished basement",
            "Three-car garage",
            "Covered patio",
            "Kitchen island",
            "Walk-in pantry",
        ],
        "description": "Recent ranch with an open main level, large kitchen island, and finished lower level for extra living space. A covered patio and three-car garage add everyday convenience.",
        "mls_number": "DEMO-002",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Campus Grove Condo",
        "status": "Active",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": True,
        "price": 224000,
        "property_type": "Condo",
        "address": "615 College Grove Way Unit 204",
        "city": "Ames",
        "state": "IA",
        "bedrooms": 2,
        "bathrooms": 3.0,
        "sqft": 1110,
        "acreage": 0.00,
        "year_built": 2007,
        "annual_property_taxes": None,
        "hoa_fee": None,
        "hoa_fee_frequency": "Monthly",
        "school_district": "Ames Community School District",
        "amenities": [
            "Balcony",
            "Secure entry",
            "Assigned parking",
            "In-unit laundry",
            "Elevator",
        ],
        "description": "Low-maintenance two-bedroom condo with an efficient open layout, private balcony, and in-unit laundry. Secure entry and assigned parking make it a straightforward option for buyers who want convenience.",
        "mls_number": "DEMO-003",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Cardinal Ridge Mid-Century Ranch",
        "status": "Pending",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 365000,
        "property_type": "Single Family",
        "address": "2417 Cardinal Ridge Road",
        "city": "Ames",
        "state": "IA",
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1960,
        "acreage": 0.27,
        "year_built": 1964,
        "annual_property_taxes": None,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Ames Community School District",
        "amenities": [
            "Brick fireplace",
            "Screened porch",
            "Mature trees",
            "Built-in shelving",
            "Attached garage",
        ],
        "description": "Mid-century ranch with broad windows, a brick fireplace, and original built-in details balanced by thoughtful updates. The screened porch opens to a shaded yard with mature trees.",
        "mls_number": "DEMO-004",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Somerset Modern Townhouse",
        "status": "Active",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 389000,
        "property_type": "Townhouse",
        "address": "3329 Alder Commons",
        "city": "Ames",
        "state": "IA",
        "bedrooms": 3,
        "bathrooms": 2.5,
        "sqft": 1780,
        "acreage": 0.08,
        "year_built": 2021,
        "annual_property_taxes": None,
        "hoa_fee": None,
        "hoa_fee_frequency": "Monthly",
        "school_district": "Ames Community School District",
        "amenities": [
            "Quartz countertops",
            "Attached garage",
            "Patio",
            "Walk-in closet",
            "Upper-level laundry",
        ],
        "description": "Modern townhouse with clean lines, quartz counters, and an open kitchen-to-living area. Upstairs laundry and an attached garage keep the layout practical without sacrificing style.",
        "mls_number": "DEMO-005",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Willow Creek Two-Story",
        "status": "Active",
        "is_public": True,
        "is_featured": True,
        "hide_exact_address": False,
        "price": 525000,
        "property_type": "Single Family",
        "address": "1712 Willow Creek Court",
        "city": "Gilbert",
        "state": "IA",
        "bedrooms": 4,
        "bathrooms": 3.0,
        "sqft": 2650,
        "acreage": 0.34,
        "year_built": 2014,
        "annual_property_taxes": 6620,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Gilbert Community School District",
        "amenities": ["Mudroom", "Fireplace", "Home office", "Three-car garage", "Large deck"],
        "description": "Four-bedroom home with a dedicated office, practical mudroom, and generous main-floor gathering spaces. The large deck overlooks a broad backyard suited to everyday outdoor living.",
        "mls_number": "DEMO-006",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Meadow Park Starter Ranch",
        "status": "Active",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 249000,
        "property_type": "Single Family",
        "address": "704 Meadow Park Avenue",
        "city": "Nevada",
        "state": "IA",
        "bedrooms": 3,
        "bathrooms": 1.5,
        "sqft": 1380,
        "acreage": 0.19,
        "year_built": 1978,
        "annual_property_taxes": 3210,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Nevada Community School District",
        "amenities": ["Eat-in kitchen", "Attached garage", "Storage shed", "Updated flooring", "Patio"],
        "description": "Straightforward three-bedroom ranch with updated flooring, an eat-in kitchen, and an attached garage. A backyard patio and storage shed add useful space without adding maintenance complexity.",
        "mls_number": "DEMO-007",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Timberline Acreage Farmhouse",
        "status": "Active",
        "is_public": True,
        "is_featured": True,
        "hide_exact_address": True,
        "price": 579000,
        "property_type": "Farm/Ranch",
        "address": "1884 Timberline Trail",
        "city": "Nevada",
        "state": "IA",
        "bedrooms": 4,
        "bathrooms": 2.5,
        "sqft": 2900,
        "acreage": 4.80,
        "year_built": 1918,
        "annual_property_taxes": 5480,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Nevada Community School District",
        "amenities": ["Barn", "Workshop", "Wraparound porch", "Updated kitchen", "Mature windbreak"],
        "description": "Updated farmhouse on nearly five acres with a wraparound porch, usable barn, and separate workshop. Mature trees frame the property while the renovated kitchen keeps the interior comfortable for modern living.",
        "mls_number": "DEMO-008",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Ballard Crossing Townhouse",
        "status": "Pending",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 319000,
        "property_type": "Townhouse",
        "address": "416 Ballard Crossing",
        "city": "Huxley",
        "state": "IA",
        "bedrooms": 2,
        "bathrooms": 2.5,
        "sqft": 1490,
        "acreage": 0.07,
        "year_built": 2019,
        "annual_property_taxes": 4210,
        "hoa_fee": 150,
        "hoa_fee_frequency": "Monthly",
        "school_district": "Ballard Community School District",
        "amenities": ["Two-car garage", "Breakfast bar", "Patio", "Walk-in closets", "Upper-level laundry"],
        "description": "Two-bedroom townhouse with an efficient open main floor, attached two-car garage, and private patio. Both bedrooms include generous closet space, while upstairs laundry keeps daily routines simple.",
        "mls_number": "DEMO-009",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Prairie Vista New Construction",
        "status": "Active",
        "is_public": True,
        "is_featured": True,
        "hide_exact_address": False,
        "price": 649000,
        "property_type": "Single Family",
        "address": "1208 Prairie Vista Circle",
        "city": "Huxley",
        "state": "IA",
        "bedrooms": 5,
        "bathrooms": 3.5,
        "sqft": 3120,
        "acreage": 0.29,
        "year_built": 2026,
        "annual_property_taxes": 7280,
        "hoa_fee": 240,
        "hoa_fee_frequency": "Annually",
        "school_district": "Ballard Community School District",
        "amenities": ["Walk-in pantry", "Finished basement", "Covered deck", "Electric fireplace", "Three-car garage"],
        "description": "New-construction five-bedroom home with a large walk-in pantry, finished lower level, and covered deck. The open main floor and three-car garage are designed for a busy household.",
        "mls_number": "DEMO-010",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Cedar Bluff Brick Ranch",
        "status": "Active",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 279000,
        "property_type": "Single Family",
        "address": "836 Cedar Bluff Drive",
        "city": "Boone",
        "state": "IA",
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1740,
        "acreage": 0.24,
        "year_built": 1958,
        "annual_property_taxes": 3510,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Boone Community School District",
        "amenities": ["Brick fireplace", "Finished lower level", "Attached garage", "Corner lot", "Updated bath"],
        "description": "Solid brick ranch with a fireplace, finished lower-level flex space, and an attached garage. The corner lot provides a little extra breathing room while keeping maintenance manageable.",
        "mls_number": "DEMO-011",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Railway District Brick Duplex",
        "status": "Sold",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 379000,
        "property_type": "Multi-Family",
        "address": "521 Railway Garden Street",
        "city": "Boone",
        "state": "IA",
        "bedrooms": 4,
        "bathrooms": 2.0,
        "sqft": 2320,
        "acreage": 0.18,
        "year_built": 1948,
        "annual_property_taxes": 4460,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Boone Community School District",
        "amenities": ["Two units", "Separate entrances", "Off-street parking", "Shared backyard", "Updated kitchens"],
        "description": "Brick duplex with two separately accessed units, updated kitchens, and off-street parking. The layout provides a useful multi-family example for the demo catalog and filtering tools.",
        "mls_number": "DEMO-012",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "District One-Bedroom Condo",
        "status": "Active",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": True,
        "price": 179000,
        "property_type": "Condo",
        "address": "1040 District Walk Unit 312",
        "city": "Ankeny",
        "state": "IA",
        "bedrooms": 1,
        "bathrooms": 1.0,
        "sqft": 820,
        "acreage": 0.00,
        "year_built": 2016,
        "annual_property_taxes": 2410,
        "hoa_fee": 220,
        "hoa_fee_frequency": "Monthly",
        "school_district": "Ankeny Community School District",
        "amenities": ["Secure entry", "Fitness room", "Balcony", "Reserved parking", "In-unit laundry"],
        "description": "Compact one-bedroom condo with a private balcony, in-unit laundry, and access to a shared fitness room. This is the catalog's lowest-price and smallest-square-footage example.",
        "mls_number": "DEMO-013",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Deer Creek Family Two-Story",
        "status": "Active",
        "is_public": True,
        "is_featured": True,
        "hide_exact_address": False,
        "price": 559000,
        "property_type": "Single Family",
        "address": "2316 Deer Creek Hollow",
        "city": "Ankeny",
        "state": "IA",
        "bedrooms": 4,
        "bathrooms": 3.5,
        "sqft": 3050,
        "acreage": 0.28,
        "year_built": 2017,
        "annual_property_taxes": 7150,
        "hoa_fee": 300,
        "hoa_fee_frequency": "Annually",
        "school_district": "Ankeny Community School District",
        "amenities": ["Home office", "Finished basement", "Covered deck", "Three-car garage", "Drop zone"],
        "description": "Spacious two-story with a dedicated office, finished basement, and covered deck. A three-car garage and organized drop zone give the home plenty of practical storage.",
        "mls_number": "DEMO-014",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Northview Modern Estate",
        "status": "Active",
        "is_public": True,
        "is_featured": True,
        "hide_exact_address": True,
        "price": 949000,
        "property_type": "Single Family",
        "address": "3810 Northview Crest",
        "city": "Ankeny",
        "state": "IA",
        "bedrooms": 5,
        "bathrooms": 4.5,
        "sqft": 4450,
        "acreage": 0.61,
        "year_built": 2023,
        "annual_property_taxes": 12600,
        "hoa_fee": 480,
        "hoa_fee_frequency": "Annually",
        "school_district": "Ankeny Community School District",
        "amenities": ["Chef kitchen", "Butler pantry", "Home gym", "Wet bar", "Outdoor fireplace", "Four-car garage"],
        "description": "Large modern home with an expansive kitchen, butler pantry, lower-level wet bar, and dedicated gym. Outdoor living centers on a covered patio and fireplace overlooking a deep lot.",
        "mls_number": "DEMO-015",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Garden Gate Cottage",
        "status": "Draft",
        "is_public": False,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 214000,
        "property_type": "Single Family",
        "address": "722 Garden Gate Lane",
        "city": "Ames",
        "state": "IA",
        "bedrooms": 2,
        "bathrooms": 1.0,
        "sqft": 1020,
        "acreage": 0.16,
        "year_built": 1941,
        "annual_property_taxes": 2860,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Ames Community School District",
        "amenities": ["Arched doorway", "Hardwood floors", "Screened porch", "Garden beds", "Detached garage"],
        "description": "Small 1940s cottage with hardwood floors, an arched doorway, and a screened porch. This listing is intentionally left in Draft status to exercise the admin-only workflow.",
        "mls_number": "DEMO-016",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Oak Hollow Split-Level",
        "status": "Active",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 295000,
        "property_type": "Single Family",
        "address": "623 Oak Hollow Road",
        "city": "Gilbert",
        "state": "IA",
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1650,
        "acreage": 0.23,
        "year_built": 1986,
        "annual_property_taxes": 3670,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Gilbert Community School District",
        "amenities": ["Lower-level family room", "Deck", "Two-car garage", "Updated kitchen", "Fire pit"],
        "description": "Well-kept split-level with an updated kitchen and a comfortable lower-level family room. A rear deck and simple fire-pit area extend the living space outdoors.",
        "mls_number": "DEMO-017",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Carousel View Ranch",
        "status": "Pending",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 309000,
        "property_type": "Single Family",
        "address": "455 Carousel View Lane",
        "city": "Story City",
        "state": "IA",
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1720,
        "acreage": 0.25,
        "year_built": 1995,
        "annual_property_taxes": 3940,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Roland-Story Community School District",
        "amenities": ["Sunroom", "Gas fireplace", "Two-car garage", "Main-floor laundry", "Storage room"],
        "description": "Comfortable 1990s ranch with main-floor laundry, a bright sunroom, and a gas fireplace. The simple layout works well for buyers who want one-level living.",
        "mls_number": "DEMO-018",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Prairie Court Manufactured Home",
        "status": "Sold",
        "is_public": True,
        "is_featured": False,
        "hide_exact_address": False,
        "price": 189000,
        "property_type": "Manufactured Home",
        "address": "87 Prairie Court",
        "city": "Ames",
        "state": "IA",
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1456,
        "acreage": 0.14,
        "year_built": 2012,
        "annual_property_taxes": 2190,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Ames Community School District",
        "amenities": ["Open kitchen", "Primary suite", "Storage shed", "Covered entry", "Off-street parking"],
        "description": "Well-maintained manufactured home with an open kitchen, primary suite, and useful outdoor storage. It gives the demo catalog a lower-cost property type beyond condos.",
        "mls_number": "DEMO-019",
        "source_attribution": "Fictional portfolio demo listing",
    },
    {
        "title": "Skunk River Country Estate",
        "status": "Active",
        "is_public": True,
        "is_featured": True,
        "hide_exact_address": True,
        "price": 825000,
        "property_type": "Farm/Ranch",
        "address": "2765 River Prairie Road",
        "city": "Story City",
        "state": "IA",
        "bedrooms": 4,
        "bathrooms": 3.0,
        "sqft": 3300,
        "acreage": 12.50,
        "year_built": 2005,
        "annual_property_taxes": 8120,
        "hoa_fee": None,
        "hoa_fee_frequency": None,
        "school_district": "Roland-Story Community School District",
        "amenities": ["Outbuilding", "Pond", "Walkout basement", "Screened porch", "Three-car garage", "Prairie views"],
        "description": "Country property on more than twelve acres with a pond, outbuilding, screened porch, and walkout lower level. The home is designed around broad rural views while staying practical for everyday use.",
        "mls_number": "DEMO-020",
        "source_attribution": "Fictional portfolio demo listing",
    },
]
